import React from './src/react.js';
import ReactDOM from './src/react-dom.js';

const {
  Children,
  createRef,
  Component,
  PureComponent,
  createContext,
  forwardRef,
  lazy,
  memo,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useDebugValue,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  Fragment,
  StrictMode,
  Suspense,
  createElement,
  cloneElement,
  createFactory,
  isValidElement,
  version,
  unstable_ConcurrentMode,
  unstable_Profiler,
  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED
} = React;

export {
  React,
  ReactDOM,
  Children,
  createRef,
  Component,
  PureComponent,
  createContext,
  forwardRef,
  lazy,
  memo,
  useCallback,
  useContext,
  useEffect,
  useImperativeHandle,
  useDebugValue,
  useLayoutEffect,
  useMemo,
  useReducer,
  useRef,
  useState,
  Fragment,
  StrictMode,
  Suspense,
  createElement,
  cloneElement,
  createFactory,
  isValidElement,
  version,
  unstable_ConcurrentMode,
  unstable_Profiler,
  __SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED
};

export default React;
